name: CI

on:
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MUMBAI_RPC_URL: https://rpc-mumbai.matic.today/
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --force

      - name: Run tests
        run: npm run coverage

      - name: Publish coverage report
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ github.token }}
          coverage_path: "coverage/coverage-summary.json"
          threshold_alert: 60
          threshold_warning: 80
          threshold_metric: "lines"